### PR TITLE
install.bash: automatically add lines to .bashrc / .bash_profile

### PR DESCRIPTION
**Pull request by PhillipSz**
hopefully you can use tput on mac, if not we can just drop that.

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Wow, :+1: 

Maybe we could also source the .bashrc automatically?

**Comment by PhillipSz** [comment]
hmm I dont think there is an easy way to that. :)

**Comment by raoulvdberge** [comment]
Isn't there the source command?

**Comment by PhillipSz** [comment]
yeah, but then you source it for the script that runs it and not for the interactive shell.

**Comment by raoulvdberge** [comment]
Ah, ok.

**Comment by eleweek** [comment]
Very nice, thank you! 

> hopefully you can use tput on mac

Worked fine on my osx, no need to update the PR.

**Pull request merged**
