### PR TITLE
Add humanized time-since on shared commands.

### PR DESCRIPTION
**Pull request by patallen**
This is my first-ever pull request :) - please forgive me if this is not how it works...

I've added a template filter that 'humanizes' the time since a date (e.g. '2 hours ago') and did a tiny bit of editing in index.html to use it to display the time since a command was shared. (Added the template tag and filter, as well as pulled the command buttons to the right)

Preview:

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Relevant issue: #26

Can you use the [humanize](https://pypi.python.org/pypi/humanize) package for returning the humanized time?

**Comment by patallen** [comment]
Hey @raoulvdberge, cool! Reading the issue again, I realized that I had misread it. 

This isn't actually being used for 'since command was sent', but 'since command was shared'.  The filter can be used just as easily to apply to 'time since sent', though.

**Comment by patallen** [comment]
@raoulvdberge Nice, didn't realize the humanize package was already being imported and used... I have added a new commit to use humanize instead.

**Comment by raoulvdberge** [comment]
:+1:

**Comment by eleweek** [comment]
> This is my first-ever pull request :) - please forgive me if this is not how it works...

Congrats on your first PR, and welcome! Thanks for contributing!

**Pull request merged**
